import re
from database import RoadDatabase
from models import RoadSegment

class OpenRoadBot:
    def __init__(self, db: RoadDatabase):
        self.db = db

    def process_query(self, query: str) -> str:
        query = query.lower()
        
        # Determine intent
        if "complain" in query or "report" in query or "pothole" in query or "issue" in query:
            return self._handle_complaint(query)
        elif "details" in query or "info" in query or "about" in query or "status" in query or "budget" in query:
            return self._handle_lookup(query)
        else:
            # Fallback to lookup
            return self._handle_lookup(query)

    def _handle_lookup(self, query: str) -> str:
        road = self._extract_road_from_query(query)
        if not road:
            return "I couldn't identify the road you are asking about. Please provide a road name (e.g., 'details about MG Road') or coordinates (e.g., 'info at 12.97, 77.59')."
        
        return self._format_road_info(road)

    def _handle_complaint(self, query: str) -> str:
        road = self._extract_road_from_query(query)
        if not road:
            return "To file a complaint, I need to know which road. Please specify the road name or coordinates."
        
        # Extract the issue (simple approach: just take the whole query as the issue for context, or look for keywords)
        issue = "road issue"
        if "pothole" in query:
            issue = "pothole"
        elif "water" in query or "flooding" in query:
            issue = "water logging"
        elif "light" in query:
            issue = "street light malfunction"
            
        return self._route_complaint(road, issue)

    def _extract_road_from_query(self, query: str):
        # 1. Try coordinate matching (lat, lon)
        # Matches formats like "12.9716, 77.5946" or "12.9716 77.5946"
        coord_match = re.search(r'(\d+\.\d+)[\s,]+(\d+\.\d+)', query)
        if coord_match:
            lat, lon = float(coord_match.group(1)), float(coord_match.group(2))
            return self.db.find_nearest_road(lat, lon)

        # 2. Try simple name matching against all road names in the DB
        for road in self.db.roads:
            if road.road_name.lower() in query:
                return road

        return None

    def _format_road_info(self, road: RoadSegment) -> str:
        return (
            f"🛣️ **Road Information for {road.road_name} ({road.road_id})**\n"
            f"- **Type:** {road.road_type}\n"
            f"- **Contractor:** {road.contractor_name}\n"
            f"- **Last Relayed:** {road.last_relaying_date}\n"
            f"- **Budget Sanctioned:** ₹{road.budget_sanctioned:,.2f}\n"
            f"- **Budget Spent:** ₹{road.budget_spent:,.2f}\n"
            f"- **Responsible Authority:** {road.executive_engineer_name} ({road.executive_engineer_contact})"
        )

    def _route_complaint(self, road: RoadSegment, issue_type: str) -> str:
        message = (
            f"🚨 **Complaint Routed Successfully** 🚨\n\n"
            f"**To:** {road.executive_engineer_name}, Executive Engineer\n"
            f"**Contact:** {road.executive_engineer_contact}\n"
            f"**Subject:** Urgent: {issue_type.title()} reported on {road.road_name} ({road.road_id})\n"
            f"**Details:** A user has reported a {issue_type} at this location. Please initiate an inspection.\n\n"
            f"*(This is an automated message generated by Open Road AI)*"
        )
        return message
